language: minimal
branches:
  only:
    - master # build master branch only
script:
  - ./ipfilter.sh
deploy:
  provider: releases
  github_token: $GH_TOKEN
  file: blocklist.p2p
  skip_cleanup: true
  overwrite: true
