language: minimal
branches:
  only:
    - master # build master branch only
script:
  - ./ipfilter.sh
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: blocklist.p2p.gz
  skip_cleanup: true
  overwrite: true
